"""empty message

Revision ID: a9d2ee266fd0
Revises: 00ab415fd3bc
Create Date: 2024-11-11 10:08:33.047928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d2ee266fd0'
down_revision = '00ab415fd3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_material_name', sa.String(), nullable=True),
    sa.Column('raw_material_code', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_material')
    # ### end Alembic commands ###
